import { readFileSync, readdirSync, lstatSync, existsSync } from 'node:fs';
import { resolve, relative, dirname, sep, posix } from 'node:path';
import { createHash } from 'node:crypto';

export const CORE = 'skills/website-build-skill';
export const ARCHIVE = 'prompts/02-graphics-design-original.md';
export const ARCHIVE_SHA = 'd985b6fcaf5c0de9c6d60f2511bb9fa5728ad0d2d543a64a673962647ea5388a';
export const digest = bytes => createHash('sha256').update(bytes).digest('hex');

// Resolve only existing, regular, repository-owned inputs. Never follow a symlink.
export function owned(root, name, mustExist = true) {
  if (typeof name !== 'string' || !name || name.includes('\\') || name.startsWith('/') || /^[A-Za-z]:/.test(name)) throw Error('invalid owned path');
  const base = resolve(root), full = resolve(base, name);
  if (full !== base && !full.startsWith(base + sep)) throw Error('path escapes repository');
  let part = base;
  if (lstatSync(base).isSymbolicLink()) throw Error('symlink root');
  for (const segment of relative(base, full).split(sep).filter(Boolean)) {
    part = resolve(part, segment);
    // existsSync follows the link, so it is FALSE for a dangling symlink and the symlink
    // check below was skipped. An ordinary write then follows that link outside the
    // repository. lstat never follows, so it sees the link whether or not the target exists.
    let entry = null;
    try { entry = lstatSync(part); } catch { entry = null; }
    if (entry) {
      if (entry.isSymbolicLink()) throw Error('symlink path');
    } else if (mustExist) throw Error(`missing path: ${name}`);
  }
  return full;
}

export function files(root, directory = '') {
  const out = [];
  for (const item of readdirSync(owned(root, directory || '.'), { withFileTypes: true }).sort((a,b) => a.name.localeCompare(b.name, 'en'))) {
    if (['.git', 'node_modules', '.test-work', '.build-local'].includes(item.name)) continue;
    // Local, gitignored working files are not part of the published tree. Reviewing them
    // would fail the gate on notes that never ship.
    if (/^AUDIT_BRIEF.*\.md$/.test(item.name) || /\.(plan|brief)\.md$/.test(item.name) || item.name === 'notes-local') continue;
    const name = directory ? `${directory}/${item.name}` : item.name;
    if (item.isSymbolicLink()) throw Error(`symlink in public tree: ${name}`);
    if (item.isDirectory()) out.push(...files(root, name));
    else if (item.isFile()) out.push(name);
  }
  return out;
}

export const read = (root, name) => readFileSync(owned(root, name), 'utf8');
export const manifest = root => JSON.parse(read(root, `${CORE}/manifest.json`));

// Rebase rendered links; bare canonical filenames retain an explicit source-base label.
export function rebase(text, source, target) {
  const rewrite = url => {
    if (/^(?:[a-z][a-z0-9+.-]*:|\/\/)/i.test(url)) return url;
    const [file, fragment] = url.split('#');
    const destination = file ? posix.normalize(posix.join(posix.dirname(source), file)) : source;
    return posix.relative(posix.dirname(target), destination) + (fragment === undefined ? '' : '#' + fragment);
  };
  let fenced = false;
  return text.split('\n').map(line => {
    if (/^\s*(`{3,}|~{3,})/.test(line)) { fenced = !fenced; return line; }
    if (fenced) return line;
    return line.replace(/(!?\[[^\]\n]*\]\()([^\s)]+)([^)]*\))/g, (_, a, b, c) => a + rewrite(b) + c)
      .replace(/^(\s*\[[^\]]+\]:\s*)(\S+)/, (_, a, b) => a + rewrite(b))
      .replace(/((?:href|src)=["'])([^"']+)(["'])/g, (_, a, b, c) => a + rewrite(b) + c);
  }).join('\n');
}

export function generated(root) {
  const m = manifest(root), output = {};
  const byPath = new Map(m.assets.map(a => [a.path, a]));
  for (const [name, members] of Object.entries(m.bundles)) {
    if (!/^(method|prompts|playbooks|checklists|team)$/.test(name)) throw Error('unknown bundle');
    const target = `docs/bundles/${name}.md`;
    let text = `# Website build: ${name}\n\nGenerated from the canonical manifest. Do not edit this file.\n\n`;
    text += 'Bare skill paths in the included instructions resolve from the canonical skill directory.\n';
    text += 'For uploads, locate the named source section in these bundles; request an attachment when absent.\n';
    text += 'Project paths resolve only in the authorized website workspace. Native loading is UNVERIFIED.\n\n## Contents\n\n';
    for (const member of members) {
      const asset = byPath.get(member);
      if (!asset?.active || member === ARCHIVE) throw Error('inactive asset requested in active bundle');
      text += `- [${member}](../../${CORE}/${member})\n`;
    }
    for (const member of members) {
      const source = `${CORE}/${member}`;
      text += `\n<!-- BEGIN SOURCE: ${member} -->\n\n## Source: ${member}\n\n`;
      const body = read(root, source);
      text += member.endsWith('.md') ? rebase(body, source, target) : `\n\`\`\`text\n${body.trimEnd()}\n\`\`\`\n`;
      text += `\n<!-- END SOURCE: ${member} -->\n`;
    }
    if (name === 'team') {
      const source = 'adapters/grok.md';
      const manual = read(root, source).split('## Manual fallback\n')[1];
      if (!manual) throw Error('missing manual fallback');
      text += '\n' + rebase('## Manual fallback\n' + manual, source, target);
      text += '\n## Artifact ownership roster\n\n```yaml\n' + read(root, 'adapters/team.yaml').trimEnd() + '\n```\n';
    }
    output[target] = text.trimEnd() + '\n';
  }
  let index = '# website-build-skill\n\n> Research-first website instructions, role boundaries and evidence gates.\n\n';
  index += 'Generated from skills/website-build-skill/manifest.json. Published at https://github.com/aunysillyme/website-build-skill. Host loading is UNVERIFIED.\n\n## Active sources\n\n';
  for (const asset of m.assets.filter(a => a.active)) index += `- [${asset.path}](${CORE}/${asset.path}): ${asset.kind}\n`;
  index += '\n## Bundles\n\n';
  for (const name of Object.keys(m.bundles)) index += `- [${name}](docs/bundles/${name}.md): generated upload packet\n`;
  index += `\n## Inactive provenance\n\n- [Graphics original](${CORE}/${ARCHIVE}): archive only; never execute\n`;
  output['llms.txt'] = index;
  return output;
}
